// SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
// SPDX-License-Identifier: MIT
// 以上两行是 REUSE 许可声明，表明该文件遵循 MIT 许可。

//go:build !js
// +build !js
// 构建约束：仅在非 WASM/非浏览器环境构建（标准 Go 环境）。

// reflect demonstrates how with one PeerConnection you can send video to Pion and have the packets sent back
// 示例说明：用一个 PeerConnection 接收浏览器的视频，并原样回送（反射）。
package main

import (
    // 标准库：读取控制台输入、编解码、错误处理、文件 IO、字符串处理
	"bufio"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

    // Pion 拦截器框架：RTP/RTCP 处理管线
	"github.com/pion/interceptor"
	"github.com/pion/interceptor/pkg/intervalpli"
    // Pion WebRTC 主包：PeerConnection、Track 等核心 API
	"github.com/pion/webrtc/v4"
)

// nolint:gocognit, cyclop
func main() {
	// Everything below is the Pion WebRTC API! Thanks for using it ❤️.
    // 以下是 Pion WebRTC 的核心使用流程。

	// Create a MediaEngine object to configure the supported codec
	mediaEngine := &webrtc.MediaEngine{}
	// MediaEngine 用于注册本端支持的编解码器（编码能力声明）。

	// Setup the codecs you want to use.
	// We'll use a VP8 and Opus but you can also define your own
	if err := mediaEngine.RegisterCodec(webrtc.RTPCodecParameters{
		RTPCodecCapability: webrtc.RTPCodecCapability{
			MimeType: webrtc.MimeTypeVP8, ClockRate: 90000, Channels: 0, SDPFmtpLine: "", RTCPFeedback: nil,
		},
		PayloadType: 96,
	}, webrtc.RTPCodecTypeVideo); err != nil {
		panic(err)
	}
	// 注册 VP8 视频编解码能力，负载类型 96。音频（Opus）在本例未发送，因此只注册视频够用。

	// Create a InterceptorRegistry. This is the user configurable RTP/RTCP Pipeline.
	// This provides NACKs, RTCP Reports and other features. If you use `webrtc.NewPeerConnection`
	// this is enabled by default. If you are manually managing You MUST create a InterceptorRegistry
	// for each PeerConnection.
	interceptorRegistry := &interceptor.Registry{}
	// InterceptorRegistry 是 RTP/RTCP 处理插件的集合（如 NACK、统计、PLI 等）。

	// Use the default set of Interceptors
	if err := webrtc.RegisterDefaultInterceptors(mediaEngine, interceptorRegistry); err != nil {
		panic(err)
	}
	// 注册默认拦截器集合（含 NACK、RTCP 报告等），增强链路可靠性与可观测性。

	// Register a intervalpli factory
	// This interceptor sends a PLI every 3 seconds. A PLI causes a video keyframe to be generated by the sender.
	// This makes our video seekable and more error resilent, but at a cost of lower picture quality and higher bitrates
	// A real world application should process incoming RTCP packets from viewers and forward them to senders
	intervalPliFactory, err := intervalpli.NewReceiverInterceptor()
	if err != nil {
		panic(err)
	}
	interceptorRegistry.Add(intervalPliFactory)
	// 每 3 秒发送一次 PLI（Picture Loss Indication），促使对端产生关键帧，便于回放与纠错。

	// Create the API object with the MediaEngine
	api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine), webrtc.WithInterceptorRegistry(interceptorRegistry))
	// API 聚合了 SettingEngine/MediaEngine/InterceptorRegistry，后续用它来创建 PeerConnection。

	// Prepare the configuration
	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}
	// PeerConnection 配置：使用 Google 公网 STUN 获取外网可达地址。
	// Create a new RTCPeerConnection
	peerConnection, err := api.NewPeerConnection(config)
	if err != nil {
		panic(err)
	}
	defer func() {
		if cErr := peerConnection.Close(); cErr != nil {
			fmt.Printf("cannot close peerConnection: %v\n", cErr)
		}
	}()
	// 延迟关闭，确保进程退出前释放资源。

	// Create Track that we send video back to browser on
	outputTrack, err := webrtc.NewTrackLocalStaticRTP(
		webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeVP8}, "video", "pion",
	)
	if err != nil {
		panic(err)
	}
	// 创建本地输出视频轨（VP8），用于将接收的视频写回浏览器。

	// Add this newly created track to the PeerConnection
	rtpSender, err := peerConnection.AddTrack(outputTrack)
	if err != nil {
		panic(err)
	}
	// 将输出轨添加进 PeerConnection，返回 RTPSender 用于 RTCP 交互。

	// Read incoming RTCP packets
	// Before these packets are returned they are processed by interceptors. For things
	// like NACK this needs to be called.
	go func() {
		rtcpBuf := make([]byte, 1500)
		for {
			if _, _, rtcpErr := rtpSender.Read(rtcpBuf); rtcpErr != nil {
				return
			}
		}
	}()
	// 异步读取入站 RTCP（来自对端：接收报告、NACK 等），以驱动拦截器链路的反馈逻辑。

	// Wait for the offer to be pasted
	offer := webrtc.SessionDescription{}
	decode(readUntilNewline(), &offer)
	// 从标准输入读取浏览器传来的 Offer（base64 编码的 SDP），解码并反序列化为 SessionDescription。

	// Set the remote SessionDescription
	err = peerConnection.SetRemoteDescription(offer)
	if err != nil {
		panic(err)
	}
	// 设置远端描述（对端浏览器的 Offer），驱动本端进入应答流程。

	// Set a handler for when a new remote track starts, this handler copies inbound RTP packets,
	// replaces the SSRC and sends them back
	peerConnection.OnTrack(func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) { //nolint: revive
		fmt.Printf("Track has started, of type %d: %s \n", track.PayloadType(), track.Codec().MimeType)
		for {
			// Read RTP packets being sent to Pion
			rtp, _, readErr := track.ReadRTP()
			if readErr != nil {
				panic(readErr)
			}

			if writeErr := outputTrack.WriteRTP(rtp); writeErr != nil {
				panic(writeErr)
			}
		}
	})
	// 当远端新轨到来：持续读取远端 RTP 包，并直接写入本地输出轨，实现“原样回送”。
	// 注意：outputTrack 的 SSRC 等由本端决定，这里相当于内容转发而非字节透明转发。

	// Set the handler for Peer connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnConnectionStateChange(func(state webrtc.PeerConnectionState) {
		fmt.Printf("Peer Connection State has changed: %s\n", state.String())

		if state == webrtc.PeerConnectionStateFailed {
			// Wait until PeerConnection has had no network activity for 30 seconds or another failure.
			// It may be reconnected using an ICE Restart.
			// Use webrtc.PeerConnectionStateDisconnected if you are interested in detecting faster timeout.
			// Note that the PeerConnection may come back from PeerConnectionStateDisconnected.
			fmt.Println("Peer Connection has gone to failed exiting")
			os.Exit(0)
		}

		if state == webrtc.PeerConnectionStateClosed {
			// PeerConnection was explicitly closed. This usually happens from a DTLS CloseNotify
			fmt.Println("Peer Connection has gone to closed exiting")
			os.Exit(0)
		}
	})
	// 连接状态回调：打印状态；Failed/Closed 时退出进程（示例程序的简化处理）。

	// Create an answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}
	// 生成本端的 SDP Answer。

	// Create channel that is blocked until ICE Gathering is complete
	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)
	// 返回一个通道：当 ICE 候选收集完成会关闭该通道，用于实现非 Trickle ICE（一次性发送完整候选）。

	// Sets the LocalDescription, and starts our UDP listeners
	if err = peerConnection.SetLocalDescription(answer); err != nil {
		panic(err)
	}
	// 设置本地描述，同时启动底层网络收发。

	// Block until ICE Gathering is complete, disabling trickle ICE
	// we do this because we only can exchange one signaling message
	// in a production application you should exchange ICE Candidates via OnICECandidate
	<-gatherComplete
	// 阻塞等待 ICE 候选全部收集完毕；示例只交换一次信令，故禁用 Trickle。

	// Output the answer in base64 so we can paste it in browser
	fmt.Println(encode(peerConnection.LocalDescription()))
	// 输出 base64 编码的 Answer（供浏览器粘贴）。

	// Block forever
	select {}
	// 选择阻塞保持进程运行（直到被外部中断）。
}

// Read from stdin until we get a newline.
func readUntilNewline() (in string) {
	var err error

	r := bufio.NewReader(os.Stdin)
	for {
		in, err = r.ReadString('\n')
		if err != nil && !errors.Is(err, io.EOF) {
			panic(err)
		}

		if in = strings.TrimSpace(in); len(in) > 0 {
			break
		}
	}

	fmt.Println("")

	return
}
	// 从 stdin 读取直到遇到换行；去除空白并返回有效字符串。

// JSON encode + base64 a SessionDescription.
func encode(obj *webrtc.SessionDescription) string {
	b, err := json.Marshal(obj)
	if err != nil {
		panic(err)
	}

	return base64.StdEncoding.EncodeToString(b)
}
	// 将 SessionDescription JSON 序列化并进行 base64 编码。

// Decode a base64 and unmarshal JSON into a SessionDescription.
func decode(in string, obj *webrtc.SessionDescription) {
	b, err := base64.StdEncoding.DecodeString(in)
	if err != nil {
		panic(err)
	}

	if err = json.Unmarshal(b, obj); err != nil {
		panic(err)
	}
}
	// 对输入进行 base64 解码，并反序列化为 SessionDescription 对象。
