// SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
// SPDX-License-Identifier: MIT
// 许可声明：MIT；该示例演示“一次上行，多路下发”的广播场景。

//go:build !js
// +build !js

// broadcast demonstrates how to broadcast a video to many peers, while only requiring the broadcaster to upload once.
// 示例说明：发布者只上传一次视频，服务端将该视频转发给多个订阅者（SFU 模式）。
package main

import (
    // 标准库依赖：HTTP、JSON/Base64 编解码、错误处理、命令行参数、打印与 I/O
    "encoding/base64"
    "encoding/json"
    "errors"
    "flag"
    "fmt"
    "io"
    "net/http"
    "strconv"

    // Pion 拦截器：RTCP/RTP 处理管线
    "github.com/pion/interceptor"
    "github.com/pion/interceptor/pkg/intervalpli"
    // Pion WebRTC 主包
    "github.com/pion/webrtc/v4"
)

// nolint:gocognit, cyclop
func main() {
    port := flag.Int("port", 8080, "http server port")
    flag.Parse()
    // 从命令行读取 HTTP 端口，默认 8080。

    sdpChan := httpSDPServer(*port)
    // 启动一个简易 HTTP 服务：接收浏览器发来的 base64 SDP（Offer），通过通道传递。

    // Everything below is the Pion WebRTC API, thanks for using it ❤️.
    offer := webrtc.SessionDescription{}
    decode(<-sdpChan, &offer)
    fmt.Println("")
    // 阻塞等待第一个发布者的浏览器 SDP（Offer），解码为 SessionDescription。

    peerConnectionConfig := webrtc.Configuration{
        ICEServers: []webrtc.ICEServer{
            {
                URLs: []string{"stun:stun.l.google.com:19302"},
            },
        },
    }
    // PeerConnection 配置：使用公共 STUN 服务器收集候选。

    mediaEngine := &webrtc.MediaEngine{}
    if err := mediaEngine.RegisterDefaultCodecs(); err != nil {
        panic(err)
    }
    // 注册默认媒体编码：使服务端能接收并转发常见编解码格式（如 VP8）。

    // Create a InterceptorRegistry. This is the user configurable RTP/RTCP Pipeline.
    // This provides NACKs, RTCP Reports and other features. If you use `webrtc.NewPeerConnection`
    // this is enabled by default. If you are manually managing You MUST create a InterceptorRegistry
    // for each PeerConnection.
    interceptorRegistry := &interceptor.Registry{}
    // 创建拦截器注册表：用于处理 NACK、RTCP 报告等。

    // Use the default set of Interceptors
    if err := webrtc.RegisterDefaultInterceptors(mediaEngine, interceptorRegistry); err != nil {
        panic(err)
    }
    // 启用默认拦截器集合。

    // Register a intervalpli factory
    // This interceptor sends a PLI every 3 seconds. A PLI causes a video keyframe to be generated by the sender.
    // This makes our video seekable and more error resilent, but at a cost of lower picture quality and higher bitrates
    // A real world application should process incoming RTCP packets from viewers and forward them to senders
    intervalPliFactory, err := intervalpli.NewReceiverInterceptor()
    if err != nil {
        panic(err)
    }
    interceptorRegistry.Add(intervalPliFactory)
    // 注册“周期性 PLI”拦截器：每 3 秒请求关键帧，使视频更易恢复与可定位（代价是质量与码率）。

    // Create a new RTCPeerConnection
    peerConnection, err := webrtc.NewAPI(
        webrtc.WithMediaEngine(mediaEngine),
        webrtc.WithInterceptorRegistry(interceptorRegistry),
    ).NewPeerConnection(peerConnectionConfig)
    if err != nil {
        panic(err)
    }
    defer func() {
        if cErr := peerConnection.Close(); cErr != nil {
            fmt.Printf("cannot close peerConnection: %v\n", cErr)
        }
    }()
    // 创建用于接入发布者的 PeerConnection，并在退出时关闭。

    // Allow us to receive 1 video track
    if _, err = peerConnection.AddTransceiverFromKind(webrtc.RTPCodecTypeVideo); err != nil {
        panic(err)
    }
    // 添加一个视频收发器：允许接收远端的视频轨。

    localTrackChan := make(chan *webrtc.TrackLocalStaticRTP)
    // Set a handler for when a new remote track starts, this just distributes all our packets
    // to connected peers
    peerConnection.OnTrack(func(remoteTrack *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) { //nolint: revive
        // Create a local track, all our SFU clients will be fed via this track
        localTrack, newTrackErr := webrtc.NewTrackLocalStaticRTP(remoteTrack.Codec().RTPCodecCapability, "video", "pion")
        if newTrackErr != nil {
            panic(newTrackErr)
        }
        localTrackChan <- localTrack
        // 收到发布者的远端轨时：创建一个“本地静态 RTP 轨”，后续订阅者将复用此轨收流。

        rtpBuf := make([]byte, 1400)
        for {
            i, _, readErr := remoteTrack.Read(rtpBuf)
            if readErr != nil {
                panic(readErr)
            }

            // ErrClosedPipe means we don't have any subscribers, this is ok if no peers have connected yet
            if _, err = localTrack.Write(rtpBuf[:i]); err != nil && !errors.Is(err, io.ErrClosedPipe) {
                panic(err)
            }
        }
    })
    // 循环读取远端轨 RTP 包，并写入到本地轨（广播给所有订阅者）。没有订阅者时可能返回 ErrClosedPipe。

    // Set the remote SessionDescription
    err = peerConnection.SetRemoteDescription(offer)
    if err != nil {
        panic(err)
    }
    // 设置发布者的 Offer 为远端描述。

    // Create answer
    answer, err := peerConnection.CreateAnswer(nil)
    if err != nil {
        panic(err)
    }
    // 生成并设置本端 Answer。

    // Create channel that is blocked until ICE Gathering is complete
    gatherComplete := webrtc.GatheringCompletePromise(peerConnection)
    // 返回一个通道：当 ICE 候选收集完成时关闭；本示例不使用 Trickle。

    // Sets the LocalDescription, and starts our UDP listeners
    err = peerConnection.SetLocalDescription(answer)
    if err != nil {
        panic(err)
    }
    // 设置本地描述并启动网络监听。

    // Block until ICE Gathering is complete, disabling trickle ICE
    // we do this because we only can exchange one signaling message
    // in a production application you should exchange ICE Candidates via OnICECandidate
    <-gatherComplete
    // 等待收集候选完成后再输出 SDP。

    // Get the LocalDescription and take it to base64 so we can paste in browser
    fmt.Println(encode(peerConnection.LocalDescription()))
    // 打印本端 Answer（base64），供发布者浏览器设置。

    localTrack := <-localTrackChan
    // 等待本地广播轨可用（收到发布者的远端轨后创建）。
    for {
        fmt.Println("")
        fmt.Println("Curl an base64 SDP to start sendonly peer connection")
        // 提示：通过 HTTP POST 发送订阅者的 SDP（Offer），启动只发送到订阅者的连接。

        recvOnlyOffer := webrtc.SessionDescription{}
        decode(<-sdpChan, &recvOnlyOffer)
        // 接收下一个订阅者的 Offer。

        // Create a new PeerConnection
        peerConnection, err := webrtc.NewPeerConnection(peerConnectionConfig)
        if err != nil {
            panic(err)
        }
        // 为订阅者创建新的 PeerConnection。

        rtpSender, err := peerConnection.AddTrack(localTrack)
        if err != nil {
            panic(err)
        }
        // 将广播用的本地轨添加到订阅者连接上，实现“一推多收”。

        // Read incoming RTCP packets
        // Before these packets are returned they are processed by interceptors. For things
        // like NACK this needs to be called.
        go func() {
            rtcpBuf := make([]byte, 1500)
            for {
                if _, _, rtcpErr := rtpSender.Read(rtcpBuf); rtcpErr != nil {
                    return
                }
            }
        }()
        // 读取订阅者的 RTCP（例如 NACK），让拦截器正确处理重传等。

        // Set the remote SessionDescription
        err = peerConnection.SetRemoteDescription(recvOnlyOffer)
        if err != nil {
            panic(err)
        }
        // 设置订阅者的 Offer 为远端描述。

        // Create answer
        answer, err := peerConnection.CreateAnswer(nil)
        if err != nil {
            panic(err)
        }
        // 为订阅者生成 Answer。

        // Create channel that is blocked until ICE Gathering is complete
        gatherComplete = webrtc.GatheringCompletePromise(peerConnection)

        // Sets the LocalDescription, and starts our UDP listeners
        err = peerConnection.SetLocalDescription(answer)
        if err != nil {
            panic(err)
        }
        // 设置本地描述并启动网络。

        // Block until ICE Gathering is complete, disabling trickle ICE
        // we do this because we only can exchange one signaling message
        // in a production application you should exchange ICE Candidates via OnICECandidate
        <-gatherComplete
        // 等待候选收集完成。

        // Get the LocalDescription and take it to base64 so we can paste in browser
        fmt.Println(encode(peerConnection.LocalDescription()))
        // 打印订阅者用的 Answer（base64），供其浏览器设置，完成观看。
    }
}

// JSON encode + base64 a SessionDescription.
func encode(obj *webrtc.SessionDescription) string {
    b, err := json.Marshal(obj)
    if err != nil {
        panic(err)
    }

    return base64.StdEncoding.EncodeToString(b)
}
// 将 SessionDescription JSON 编码后再 base64，方便通过简单文本传输。

// Decode a base64 and unmarshal JSON into a SessionDescription.
func decode(in string, obj *webrtc.SessionDescription) {
    b, err := base64.StdEncoding.DecodeString(in)
    if err != nil {
        panic(err)
    }

    if err = json.Unmarshal(b, obj); err != nil {
        panic(err)
    }
}
// 解析 base64 并反序列化 JSON 为 SessionDescription。

// httpSDPServer starts a HTTP Server that consumes SDPs.
func httpSDPServer(port int) chan string {
    sdpChan := make(chan string)
    http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
        body, _ := io.ReadAll(req.Body)
        fmt.Fprintf(res, "done") //nolint: errcheck
        sdpChan <- string(body)
    })
    // 根路径 POST：读取请求体（base64 SDP）并写入通道；响应 "done"。

    go func() {
        // nolint: gosec
        panic(http.ListenAndServe(":"+strconv.Itoa(port), nil))
    }()
    // 启动 HTTP 服务器；异常直接 panic，示例场景下可接受。

    return sdpChan
}
// 返回一个通道：用于将收到的 SDP 文本传给主逻辑（发布者与订阅者）。
